#pragma once

const char * frag_csm_debug_source =
"#version 330 core\n"
"out vec4 FragColor;\n"
"\n"
"in vec2 TexCoords;\n"
"\n"
"uniform sampler2D depthMap;\n"
"uniform int cascadeLevel;\n"
"\n"
"void main() {\n"
"  float depthValue = texture(depthMap, TexCoords).r;\n"
"\n"
"  // Visualize different cascades with different colors\n"
"  vec3 cascadeColors[3] =\n"
"      vec3[](vec3(1.0, 0.0, 0.0), // Red for near cascade\n"
"             vec3(0.0, 1.0, 0.0), // Green for middle cascade\n"
"             vec3(0.0, 0.0, 1.0)  // Blue for far cascade\n"
"      );\n"
"\n"
"  // Enhance the visualization by using a non-linear mapping\n"
"  float enhancedDepth = pow(depthValue, 10.0);\n"
"  FragColor = vec4(cascadeColors[cascadeLevel] * enhancedDepth, 1.0);\n"
"}\n"
;
