#pragma once

const char * vertex_star_source =
"// Vertex shader\n"
"#version 330 core\n"
"layout(location = 0) in vec3 aPos;\n"
"\n"
"out vec3 vertexColor;\n"
"\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 projection;\n"
"uniform vec3 color;\n"
"uniform vec3 skyColor;\n"
"uniform float starVisibility;\n"
"\n"
"void main() {\n"
"  vec4 viewPos = view * model * vec4(aPos, 1.0f);\n"
"  gl_Position = projection * viewPos;\n"
"\n"
"  float culling_d = 3000.f;\n"
"  float gray = (culling_d + viewPos.z) / culling_d;\n"
"  vertexColor = mix(skyColor, mix(skyColor, color, starVisibility), max(0.0, min(gray, 1.0)));\n"
"}\n"
;
